project:
  type: website
  output-dir: docs

website:
  title: "Leela Dixit"
  #favicon: images/favicon.png
  navbar:
    #logo: images/logo.png
    #logo-alt: alt text for my logo goes here
    #title: false
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - posts.qmd
      - href: resources.qmd
        text: Resources
      - icon: github
        href: https://github.com/lsdixit/lsdixit.github.io
  page-footer: 
    left: Copyright 2025, Leela Dixit
    right:
      - icon: github
        href: https://github.com/lsdixit/lsdixit.github.io 

format:
  html:
    theme: styles.scss
    css: styles.css
    toc: true
    page-layout: full
    mainfont: Montserrat




